# Generated by Django 2.2 on 2021-05-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210512_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
